language: generic
sudo: false

env:
  matrix:
    - EMACS_VERSION=26-pretest
    - EMACS_VERSION=25.3
    - EMACS_VERSION=24.5

before_install:
  - git clone --depth=1 https://github.com/rejeep/evm.git ./.evm
  - ./.evm/bin/evm config path /tmp
  - ./.evm/bin/evm install emacs-$EMACS_VERSION-travis --use
  - ./.evm/bin/emacs --version

script:
  make test EMACS=$PWD/.evm/bin/emacs
